---
name: traefik
version: 1.0.0
iteration: rc1
license: MIT
epoch: 414
vendor: Emile Vauge
architecture: x86_64
type: rpm
url: https://github.com/containous/traefik
description: Træfɪk, a modern reverse proxy

# this field means nothing now that they've switched from numbers to git hashes.
# However, we need to keep it around until the version actually changes. Bump
# this and iteration until then.
epoch: 414

dependencies:
  - libcap
  - python
  - sudo

resources:
  - url: '{{.URL}}/releases/download/v{{.Version}}-{{.Iteration}}/{{.Name}}_linux-amd64'
    hash-type: sha256
    hash: d3862ad9e46f3fe18a04882c71c09c748781829d8542d9c9e6954b8de167e14b

targets:
  # base
  - src: '{{.BuildRoot}}/{{.Name}}_linux-amd64'
    dest: /usr/bin/{{.Name}}
  - src: '{{.SpecRoot}}/{{.Name}}.service'
    dest: /etc/systemd/system/{{.Name}}.service
    template: yes
  - src: '{{empty}}'
    dest: /etc/{{.Name}}
  - src: '{{empty}}'
    dest: /etc/{{.Name}}/configs

  # logging
  - src: '{{.SpecRoot}}/logrotate/{{.Name}}'
    dest: /etc/logrotate.d/{{.Name}}
  - src: '{{.SpecRoot}}/logrotate/{{.Name}}-access'
    dest: /etc/logrotate.d/{{.Name}}-access
  - src: "{{empty}}"
    dest: /var/log/{{.Name}}
  - src: "{{empty}}"
    dest: /var/log/{{.Name}}/archive

  # config generation scripts
  - src: '{{.SpecRoot}}/config/'
    dest: /usr/bin/
  - src: '{{.SpecRoot}}/{{.Name}}-restart'
    dest: /etc/sudoers.d/

scripts:
  before-install: |
    getent group {{.Name}} > /dev/null || groupadd -r {{.Name}}
    getent passwd {{.Name}} > /dev/null || \
        useradd -r \
                -g {{.Name}} \
                -d /etc/{{.Name}} \
                -s /sbin/nologin \
                -c "{{.Name}} user" \
                {{.Name}}

  after-install: |
    chown -R {{.Name}}:{{.Name}} /etc/{{.Name}}
    chown -R {{.Name}}:{{.Name}} /var/log/{{.Name}}

    setcap 'cap_net_bind_service=+ep' /usr/bin/{{.Name}}

    systemctl enable /etc/systemd/system/{{.Name}}.service 2>/dev/null
    systemctl start {{.Name}}.service

    sudo -u {{.Name}} {{.Name}}-global --port=80 --grace-time-out=10
    sudo -u {{.Name}} {{.Name}}-web --address=:8080

  after-upgrade: |
    chown -R {{.Name}}:{{.Name}} /var/log/{{.Name}}

    setcap 'cap_net_bind_service=+ep' /usr/bin/{{.Name}}

    systemctl daemon-reload
    systemctl restart {{.Name}}.service

  before-remove: |
    systemctl stop {{.Name}}.service
    systemctl disable {{.Name}}.service 2>/dev/null

  after-remove: |
    systemctl daemon-reload

extra-args: |
  --rpm-os linux
  --rpm-auto-add-directories
  --rpm-auto-add-exclude-directories /etc/systemd
  --rpm-auto-add-exclude-directories /etc/systemd/system
  --rpm-auto-add-exclude-directories /etc/sudoers.d
  --rpm-auto-add-exclude-directories /etc/logrotate.d
