#!/usr/bin/env python
import argparse
import os
import subprocess
import sys
from textwrap import dedent

def parse_args(args=None):
    parser = argparse.ArgumentParser(
        __file__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument('--address', default=':8080', help='address to listen on')
    parser.add_argument('--cert-file', default='', help='certificate file to use')
    parser.add_argument('--key-file', default='', help='key file to use')
    parser.add_argument('--disable', action='store_true', help='disable web frontend')

    return parser.parse_args(args)


def get_template(address, cert_file, key_file):
    return '\n'.join([
        line for line in
        [
            '[web]',
            'address = "{}"'.format(address),
            'CertFile = "{}"'.format(cert_file) if cert_file else '',
            'KeyFile = "{}"'.format(key_file) if key_file else '',
        ]
        if line != ''
    ]) + '\n'


def main(args=None):
    args = parse_args()

    fname = '/etc/traefik/configs/web.toml'

    with open(fname, 'w') as f:
        f.write(get_template(
            args.address,
            args.cert_file,
            args.key_file,
        ))

    return subprocess.call('traefik-regen')

if __name__ == '__main__':
    sys.exit(main(sys.argv))
